//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - PRESENTATION LOGIC
protocol I___VARIABLE_sceneName___Presenter {
    func presentSomething(response: ___VARIABLE_sceneName___Model.Something.Response)
}

// MARK: - PRESENTER
class ___VARIABLE_sceneName___Presenter: I___VARIABLE_sceneName___Presenter {
    weak var viewController: I___VARIABLE_sceneName___ViewController?
}

// MARK: - DO SOMETHING
extension ___VARIABLE_sceneName___Presenter {
    func presentSomething(response: ___VARIABLE_sceneName___Model.Something.Response) {
        let viewModel = ___VARIABLE_sceneName___Model.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
