//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import ___PROJECTNAMEASIDENTIFIER___
import XCTest

// MARK: - WORKER
class ___VARIABLE_sceneName___WorkerTests: XCTestCase {
    
    // MARK: SUBJECT UNDER TEST
    var sut: ___VARIABLE_sceneName___Worker!
    
    // MARK: TEST LIFECYCLE
    override func setUp() {
        super.setUp()
        setup___VARIABLE_sceneName___Worker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: TEST SETUP
    func setup___VARIABLE_sceneName___Worker() {
        sut = ___VARIABLE_sceneName___Worker()
    }
    
    // MARK: TEST DOUBLES
    
    // MARK: TESTS
    func testSomething() {
        // Given
        
        // When
        
        // Then
    }
}
