//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import ___PROJECTNAMEASIDENTIFIER___
import XCTest

// MARK: - PRESENTER
class ___VARIABLE_sceneName___PresenterTests: XCTestCase {
    
    // MARK: SUBJECT UNDER TEST
    var sut: ___VARIABLE_sceneName___Presenter!
    
    // MARK: TEST LIFECYCLE
    override func setUp() {
        super.setUp()
        setup___VARIABLE_sceneName___Presenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: TEST SETUP
    func setup___VARIABLE_sceneName___Presenter() {
        sut = ___VARIABLE_sceneName___Presenter()
    }
    
    // MARK: TEST DOUBLES
    class ___VARIABLE_sceneName___ViewControllerSpy: I___VARIABLE_sceneName___ViewController {
        var displaySomethingCalled = false
        
        func displaySomething(viewModel: ___VARIABLE_sceneName___Model.Something.ViewModel) {
            displaySomethingCalled = true
        }
    }
    
    // MARK: TESTS
    func testPresentSomething() {
        // Given
        let spy = ___VARIABLE_sceneName___ViewControllerSpy()
        sut.viewController = spy
        let response = ___VARIABLE_sceneName___Model.Something.Response()
        
        // When
        sut.presentSomething(response: response)
        
        // Then
        XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
    }
}
