//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import ___PROJECTNAMEASIDENTIFIER___
import XCTest

// MARK: - VIEW CONTROLLER
class ___VARIABLE_sceneName___ViewControllerTests: XCTestCase {
    
    // MARK: SUBJECT UNDER TEST
    var sut: ___VARIABLE_sceneName___ViewController!
    var window: UIWindow!
    
    // MARK: TEST LIFECYCLE
    override func setUp() {
        super.setUp()
        window = UIWindow()
        setup___VARIABLE_sceneName___ViewController()
    }
    
    override func tearDown() {
        window = nil
        super.tearDown()
    }
    
    // MARK: TEST SETUP
    func setup___VARIABLE_sceneName___ViewController() {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "Main", bundle: bundle)
        sut = storyboard.instantiateViewController(withIdentifier: "___VARIABLE_sceneName___ViewController") as! ___VARIABLE_sceneName___ViewController
    }
    
    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: TEST DOUBLES
    class ___VARIABLE_sceneName___InteractorSpy: I___VARIABLE_sceneName___Interactor {
        var doSomethingCalled = false
        
        func doSomething(request: ___VARIABLE_sceneName___Model.Something.Request) {
            doSomethingCalled = true
        }
    }
    
    // MARK: TESTS
    func testShouldDoSomethingWhenViewIsLoaded()
     
        // Given
        let spy = ___VARIABLE_sceneName___InteractorSpy()
        sut.interactor = spy
        
        // When
        loadView()
        
        // Then
        XCTAssertTrue(spy.doSomethingCalled, "viewDidLoad() should ask the interactor to do something")
    }
    
    func testDisplaySomething() {
        // Given
        let viewModel = ___VARIABLE_sceneName___Model.Something.ViewModel()
        
        // When
        loadView()
        sut.displaySomething(viewModel: viewModel)
        
        // Then
        //XCTAssertEqual(sut.nameTextField.text, "", "displaySomething(viewModel:) should update the name text field")
    }
}
